name: Build Xoolal Linux
on:
  push:
    branches: ["main"]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-pyqt5 python3-pyqt5.qtwebengine
          pip install pyinstaller --break-system-packages
      - name: Build
        run: |
          pyinstaller --onefile --name=Xoolal_linux \
            --add-data="accueil.html:." \
            --hidden-import=bloqueur \
            --hidden-import=moteur \
            --hidden-import=cookies \
            navigateur.py
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Xoolal-Linux
          path: dist/Xoolal_linux
